In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1 (1).csv')

In [3]:
df

,Timestamp,How old are you?,Industry,Job title,Additional context on job title,Annual salary,Other monetary comp,Currency,Currency - other,Additional context on income,Country,State,City,Overall years of professional experience,Years of experience in field,Highest level of education completed,Gender,Race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27676,2/19/2022 16:07:31,45-54,Property or Construction,Senior Project Manager,Owner rep consultant,145000,14500.0,USD,NaN,Guaranteed 10% bonus if our department meets t...,USA,California,San Francisco,11 - 20 years,11 - 20 years,College degree,Woman,Asian or Asian American
27677,2/19/2022 18:17:08,25-34,Insurance,Underwriter,NaN,67000,6700.0,USD,NaN,NaN,USA,Florida,Tampa,8 - 10 years,11 - 20 years,Master's degree,Woman,White
27678,2/19/2022 19:47:05,25-34,"Accounting, Banking & Finance",Vice Presidenti and Corporate Counsel,(in-house attorney),252000,80000.0,USD,NaN,I also receive an equity grant,US,Pennsylvania,Philadelphia,11 - 20 years,11 - 20 years,"Professional degree (MD, JD, etc.)",Woman,White
27679,2/21/2022 19:43:29,25-34,Education (Early Childhood Education),Quality Rating Specialist,Program assessor to conduct quality assessment...,62400,NaN,USD,NaN,NaN,United States,California,San Diego,11 - 20 years,8 - 10 years,College degree,Woman,Asian or Asian American
27680,2/22/2022 13:05:17,25-34,Political Campaigns,Congressional Field Director,NaN,66000,5500.0,USD,NaN,"Paid as $5,500 monthly, with a month's salary ...",United States,Virginia,Virginia Beach,5-7 years,5-7 years,College degree,Woman,White

In [4]:
df.dtypes

Timestamp                                    object
How old are you?                             object
Industry                                     object
Job title                                    object
Additional context on job title              object
Annual salary                                object
Other monetary comp                         float64
Currency                                     object
Currency - other                             object
Additional context on income                 object
Country                                      object
State                                        object
City                                         object
Overall years of professional experience     object
Years of experience in field                 object
Highest level of education completed         object
Gender                                       object
Race                                         object
dtype: object

To do: 
1) remove timestamp
2) set How old are you? to categorical
3) refine/group industry